title: uEdition
author: Mark Hall
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/uEdition/uEdition.github.io
  path_to_book: en
  branch: main

html:
  use_issues_button: false
  use_repository_button: true
