author: Mark Hall
html:
  use_repository_button: true
repository:
  branch: main
  path: en
  url: https://github.com/uEdition/uEdition.github.io
sphinx:
  config:
    language: en
  extra_extensions:
  - uedition
title: "\u03BCEdition"
