title: Î¼Edition
author: Mark M. Hall
logo: logo.png
language: de

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - ../references.bib

repository:
  url: https://github.com/uEdition/uEdition.github.io
  path_to_book: de
  branch: main

html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  recursive_update: true
  config:
    language: de
